### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by helgestein** [helgestein/helao-pub#49]
Please add the documentation you wrote for DTU here. Maybe even as some html or markdown file.

**Comment by darthlegit** [comment]
wrote implies past tense. I am working on it right now and am hoping that I can finish tomorrow.

**Comment by darthlegit** [comment]
I am writing in latex, so it will be as pdf unless there is an easy way to convert

**Comment by darthlegit** [comment]
uploaded as pdf. markdown conversion does not preserve figures, and i am unclear as to the utility of having it in this format.
